name: .NET Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    # specify evn name configured on GitHub that include env var and secrets
    environment: sw_testing

    permissions:
      id-token: write
      contents: read
      checks: write

    steps:
      - uses: actions/checkout@v3
  
      - name: Setup .NET SDK 
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Install dependencies from NuGet Repository
        run: dotnet restore

      - name: Build project solution
        run: dotnet build --configuration Release

      - name: Run Unit Test
        if: ${{ true }}
        run: dotnet test --logger "trx;LogFileName=test-results.trx" || true

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()       # run this step even if previous step failed
        with:
          name: Tests Results            # Name of the check run which will be created
          path: "**/test-results.trx"    # Path to test results
          reporter: dotnet-trx           # Format of test results